export const SITTING_CHOSEN = "SITTING_CHOSEN";

export const CREATE_SITTING = "CREATE_SITTING";
export const EDIT_SITTING = "EDIT_SITTING";
export const SAVE_SITTING_CHANGES = "SAVE_SITTING_CHANGES";

export const CREATE_STEP = "CREATE_STEP";
export const EDIT_STEP = "EDIT_STEP";
export const SAVE_STEP_CHANGES = "SAVE_STEP_CHANGES";